config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :jobs
  resources :job_responses
  resources :profiles, only: [:index,:show, :edit, :update]
  resources :chatrooms, only: [:show, :new, :create] do
    resources :messages, only: :create
  end
  get "dashboard", to: "pages#dashboard"
  resources :private_chatrooms, only: [:show, :new, :create] do
    resources :private_messages, only: [:create, :destroy]
  end

  resources :jobs do
    resources :job_responses, only: [:new, :create]
  end
  resources :job_responses, only: [:show, :new, :update, :destroy]

  resources :tags
  resources :blogs do
    resources :blog_posts do
      resources :comments
      resources :votes
    end
  end

  resources :categories, only: [:index, :show]

  get "new_messages", to: "private_messages#new_messages"
  get "read_messages", to: "private_messages#read_messages"
  post "read_messages", to: "private_messages#read_messages"

  resources :jobs, only: [:index, :show] do
    member do
      post 'toggle_favorite', to: "jobs#toggle_favorite"
    end
  end
  # Define your job_responses routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
  has_many :blog_posts, dependent: :destroy
  has_many :blogs_tags, dependent: :destroy
  has_many :tags, through: :blogs_tags
  has_many :blog_categories, dependent: :destroy
  has_many :categories, through: :blog_categories
  has_one_attached :image
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = policy_scope(Blog)
    @categories = Category.all
    @blog_posts = BlogPost.all
    if params[:query].present?
      @query = params[:query]
      @blog_posts = BlogPost.search_by_title(@query)
    else
      @blog_posts = @blog_posts.where(blog: @blog)
      @blog_posts = BlogPost.all
    end
  end

  def show
  end

  def new
    @blog = Blog.new
    authorize @blog
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user
    authorize @blog
    if params[:blog][:tags].present?
      params[:blog][:tags].each do |tag|
        @blog.tags << Tag.find(tag)
      end
    end
    if params[:blog][:categories].present?
      params[:blog][:categories].each do |category|
        @blog.categories << Category.find(category)
      end
    end
    if @blog.save
      redirect_to blogs_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @blog.update(blog_params)
    redirect_to blog_path(@blog)
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, status: :see_other
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
    authorize @blog
  end

  def blog_params
    params.require(:blog).permit(:title, :image)
  end
end

app/views/blogs/_category_card.html.erb
<%= link_to blogs_path(query: category.name) do %>
  <div class="category-card" tabindex="<%= index %>" style="background:linear-gradient(90deg, rgba(1,9,59,0.7101123595505618) 0%, rgba(3,33,73,0.7415730337078652) 95%), url('<%= image %>'); background-size: cover;">
  <div class="category-info">
    <%#= image_tag 'https://images.pexels.com/photos/5952651/pexels-photo-5952651.jpeg?auto=compress&cs=tinysrgb&w=600' %>
    <h1> <%= category.name %></h1>
  </div>
</div>
<% end %>

app/views/blogs/edit.html.erb
<div class="container">
  <%=  simple_form_for @blog do |f| %>
    <%= f.input :title %>
    <%= f.input :categories, as: :check_boxes, collection: Category.all, label: "Categories", include_hidden: false %>
    <%= f.input :tags, as: :check_boxes, collection: Tag.all, label: "Tags", include_hidden: false %>
    <%= f.input :image, as: :file %>
    <%= f.button :submit, "Submit", class:"btn1 mt-3 mb-3"%>
  <% end %>
</div>

app/views/blogs/index.html.erb
<div class="outer-frame" data-controller="blogFilter">
  <div class="inner-button">
    <% if current_user.blogs.empty? %>
      <% Blog.create(user: current_user, title: "My Blog") %>
    <% end %>
    <%=  link_to "+", new_blog_blog_post_path(current_user.blogs.first, BlogPost.new), class:"new-button" %>
  </div>
  <div class="blog-category-banner">
    <h1>User Blog Posts</h1>
  </div>
  <form class="blog-form">
    <div class="blog-nav">
      <div class="category-search">
        <input class="search-field" name="query" type="search" placeholder="..." autocomplete="off" aria-label="Search" value="<%= params[:query] %> ">
        <%# <div class="search-field">
          ...
        </div> %>
        <button class="search-button" type="submit">
          Search
        </button>
      </div>
      <div class="filter-button" data-action="click->blogFilter#show">
        Filter
      </div>
    </div>
    <div class="outer-filter-box" data-blogFilter-target="filter">
      <% category_images = ["https://images.pexels.com/photos/1509534/pexels-photo-1509534.jpeg?auto=compress&cs=tinysrgb&w=800",
        "https://images.pexels.com/photos/1172253/pexels-photo-1172253.jpeg?auto=compress&cs=tinysrgb&w=600",
        "https://images.pexels.com/photos/132477/pexels-photo-132477.jpeg?auto=compress&cs=tinysrgb&w=600",
        "https://images.pexels.com/photos/60504/security-protection-anti-virus-software-60504.jpeg?auto=compress&cs=tinysrgb&w=600",
        "https://images.pexels.com/photos/943096/pexels-photo-943096.jpeg?auto=compress&cs=tinysrgb&w=600",
        "https://images.pexels.com/photos/4164418/pexels-photo-4164418.jpeg?auto=compress&cs=tinysrgb&w=600",
        "https://images.pexels.com/photos/1181712/pexels-photo-1181712.jpeg?auto=compress&cs=tinysrgb&w=600",
        "https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=600",
        "https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=600",
        "https://images.pexels.com/photos/574069/pexels-photo-574069.jpeg?auto=compress&cs=tinysrgb&w=600",
        "https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg?auto=compress&cs=tinysrgb&w=600",
        "https://images.pexels.com/photos/5952651/pexels-photo-5952651.jpeg?auto=compress&cs=tinysrgb&w=600"] %>
      <div class="category-filter">
        <% @categories.each_with_index do |category, index| %>
          <% image = category_images[index] %>
          <%= render "blogs/category_card", category: category, image: image, index: index %>
        <% end %>
      </div>
    </div>
  </form>
  <%# Blog category cards with iteration %>
  <div class="blog-category-list">
    <% @blog_posts.each do |post| %>
      <%= link_to blog_blog_post_path(post.blog, post) do %>
        <% if  post.image.attached? %>
          <div class="blog-category-card">
            <div class="article-img">
              <%= cl_image_tag post.image.key, class:"art-img" %>
            </div>
            <div class="post-info">
              <h2><%=  post.title %></h2>
              <h4>by <%= post.blog.user.nickname %> - <%= post.created_at.strftime(" %B %e, %Y") %></h4>
            </div>
          </div>
        <% else %>
          <div class="blog-category-card">
            <div class="article-img">
              <%= image_tag "logo_placeholder.png", class:"art-img"%>
            </div>
            <div class="post-info">
              <h2><%=  post.title %></h2>
              <h4>by <%= post.blog.user.nickname %> - <%= post.created_at.strftime(" %B %e, %Y") %></h4>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <%=  simple_form_for @blog do |f| %>
    <%= f.input :title %>
    <%= f.input :categories, as: :check_boxes, collection: Category.all, label: "Categories", include_hidden: false %>
    <%= f.input :tags, as: :check_boxes, collection: Tag.all, label: "Tags", include_hidden: false %>
    <%= f.input :image, as: :file %>
    <%= f.button :submit, "Submit", class:"btn1 mt-3 mb-3"%>
  <% end %>
</div>

app/views/blogs/show.html.erb
<div class="container">
  <h1> <%=  @blog.title %> </h1>
  <%  @blog.blog_posts.each do |blog_post| %>
    <h1> <%=  blog_post.title %> </h1>
    <%= link_to "more", blog_blog_post_path(blog_post.blog, blog_post), class: "btn btn-primary" %>
  <% end %>

  <%=  link_to "Back", blogs_path, class: "btn btn-primary" %>
  <%=  link_to "Edit", edit_blog_path(@blog), class: "btn btn-danger" %>
</div>