config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :jobs
  resources :job_responses
  resources :profiles, only: [:index,:show, :edit, :update]
  resources :chatrooms, only: [:show, :new, :create] do
    resources :messages, only: :create
  end
  get "dashboard", to: "pages#dashboard"
  resources :private_chatrooms, only: [:show, :new, :create] do
    resources :private_messages, only: [:create, :destroy]
  end

  resources :jobs do
    resources :job_responses, only: [:new, :create]
  end
  resources :job_responses, only: [:show, :new, :update, :destroy]

  resources :tags
  resources :blogs do
    resources :blog_posts do
      resources :comments
      resources :votes
    end
  end

  resources :categories, only: [:index, :show]

  get "new_messages", to: "private_messages#new_messages"
  get "read_messages", to: "private_messages#read_messages"
  post "read_messages", to: "private_messages#read_messages"

  resources :jobs, only: [:index, :show] do
    member do
      post 'toggle_favorite', to: "jobs#toggle_favorite"
    end
  end
  # Define your job_responses routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :blog, optional: true
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_one_attached :image
  has_many :blog_post_categories, dependent: :destroy
  has_many :categories, through: :blog_post_categories

  include PgSearch::Model
  pg_search_scope :search_by_title,
    against: [ :title ],
    associated_against: {
      # blog: [:.user.nickname],
      categories: [:name]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  def index
    @blog = Blog.find(params[:blog_id])
    @blog_posts = policy_scope(BlogPost)
    @blog_posts = @blog_posts.where(blog: @blog)
  end

  def show
  end

  def new
    @blog = Blog.find(params[:blog_id])
    @blog_post = BlogPost.new
    authorize @blog_post
    authorize @blog
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    @blog_post.blog = Blog.find(params[:blog_id])
    authorize @blog_post
    if params[:blog_post][:tags].present?
      params[:blog_post][:tags].each do |tag|
        @blog_post.tags << Tag.find(tag)
      end
    end
    if params[:blog_post][:categories].present?
      params[:blog_post][:categories].each do |category|
        @blog_post.categories << Category.find(category)
      end
    end
    if @blog_post.save
      redirect_to blogs_path # (@blog_post.blog) added s to blogs
    else
      render :new
    end
  end

  def edit
  end

  def update
    @blog_post.update(blog_post_params)
    redirect_to blog_blog_post_path(@blog_post.blog, @blog_post)
  end

  def destroy
    @blog_post.destroy
    redirect_to blog_posts_path, status: :see_other
  end

  private

  def set_blog_post
    @blog_post = BlogPost.find(params[:id])
    @blog = Blog.find(params[:blog_id])
    authorize @blog_post
  end

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :image)
  end
end

app/views/blog_posts/_blog_post.html.erb
<div class="post border">
      <h1> <%=  blog_post.title %> </h1>
      <%= cl_image_tag blog_post.image.key, heigth: 300, width: 300 if blog_post.image.attached? %>
      <p> <%=  blog_post.content %> </p>
      <div id="likes" class="d-flex flex-row">
        <div class="like">
          <i class="fa-solid fa-heart"></i><%=  blog_post.votes.where(value: 1).size %>
        </div>
        <div class="dislike">
          <i class="fa-solid fa-heart-crack dislike"></i><%=  blog_post.votes.where(value: -1).size %>
        </div>
      </div>
      <p> <%=  link_to "details", blog_blog_post_path(blog_post.blog, blog_post), class: "btn btn-primary" %> </p>
    </div>

app/views/blog_posts/edit.html.erb
<%=  simple_form_for [@blog, @blog_post] do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :image, as: :file %>
  <%= f.button :submit, "Submit", class:"btn1 mt-3 mb-3"%>
<% end %>

app/views/blog_posts/index.html.erb
<div class="container">
  <h1> <%=  @blog.title %> </h1>
  <%=  link_to "Back", blogs_path, class: "btn btn-primary" %>
  <%=  link_to "Edit", edit_blog_path(@blog), class: "btn btn-danger" %>
  <%= link_to "New Post", new_blog_blog_post_path(@blog), class: "btn btn-primary" %>
  <% @blog_posts.each do |blog_post| %>
    <%=  render "blog_post", blog_post: blog_post %>
  <% end %>
</div>

app/views/blog_posts/new.html.erb
<%=  simple_form_for [@blog, @blog_post] do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :categories, as: :check_boxes, collection: Category.all, label: "Categories", include_hidden: false %>
  <%= f.input :image, as: :file %>
  <%= f.button :submit, "Submit", class:"btn1 mt-3 mb-3"%>
<% end %>

app/views/blog_posts/show.html.erb
<div class="blog-post-buttons">
  <%=  link_to blogs_path, class: "btn button-back" do %>
      <i class="fa-solid fa-chevron-left"></i>
  <% end %>
  <div class="blog-meta"><%= @blog_post.created_at.strftime(" %B %e, %Y") %></div>
  <div class="blog-meta"><%= @blog.user.nickname %></div>
  <%=  link_to profile_path(@blog.user), class: "btn button-edit" do %>
      <i class="fa-solid fa-user"></i>
  <% end %>
  <%  if policy(@blog_post).edit?%>
    <%=  link_to edit_blog_blog_post_path(@blog, @blog_post), class: "btn button-edit" do %>
        <i class="fa-solid fa-pencil"></i>
    <% end %>
  <% end %>
</div>

<div class="outer-frame-post">
  <div class="blog-post-title">
    <%=  @blog_post.title %>
  </div>
  <div class="blog-post-image">
    <%= cl_image_tag @blog_post.image.key if @blog_post.image.attached? %>
  </div>

  <div class="blog-post-content-container">
    <div class="blog-post-content">
      <%=  @blog_post.content.html_safe %>
    </div>
  </div>

  <div class="votes-container">
    <div class="your-vote">
      <%# if user not voted yet %>
      <% if @blog_post.votes.where(user: current_user).size == 0 %>
        <%=  button_to blog_blog_post_votes_path(@blog, @blog_post, value: 1), method: :post, class: "like1-show" do %>
          <i class="fa-solid fa-thumbs-up"></i>
        <% end %>
        <%=  button_to blog_blog_post_votes_path(@blog, @blog_post, value: -1), method: :post, class: "dislike1-show" do %>
          <i class="fa-solid fa-thumbs-down"></i>
        <% end %>
      <% else %>
        <%# user can update vote with method patch %>
        <%=  button_to blog_blog_post_vote_path(@blog, @blog_post, @blog_post.votes.where(user: current_user).first, value: 1), method: :patch, class: "like" do %>

          <div class="total-likes-show">
            <i class="fa-solid fa-thumbs-up like2-show"></i>
            <div class="like2-text"> <%=  @blog_post.votes.where(value: 1).size %> </div>
          </div>
        <% end %>
        <%=  button_to blog_blog_post_vote_path(@blog, @blog_post, @blog_post.votes.where(user: current_user).first, value: -1), method: :patch, class: "dislike" do %>
          <div class="total-dislikes-show">
            <i class="fa-solid fa-thumbs-down dislike2-show"></i>
            <div class="dislike2-text"> <%=  @blog_post.votes.where(value: -1).size %> </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="comment-wrapper-js d-flex flex-column" data-controller="comments">
  <div class="container comment-link mb-3">
    <a href="#" data-comments-target="link" data-action="click->comments#show" class="m-3 comment-button"> Show Comments </a>
  </div>
  <div class="container border comment-wrapper d-none" data-controller="insert-in-list" data-comments-target="comm">
    <p class="border-bottom">Comments </p>
    <div class="comment-list" data-insert-in-list-target="items">
      <% @blog_post.comments.where(parent_id: nil).each do |comment| %>
        <%= render "comments/comment", comment: comment %>
      <% end %>
    </div>
    <%= render "comments/form", blog: @blog, blog_post: @blog_post, comment: Comment.new %>
  </div>