config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :jobs
  resources :job_responses
  resources :profiles, only: [:index,:show, :edit, :update]
  resources :chatrooms, only: [:show, :new, :create] do
    resources :messages, only: :create
  end
  get "dashboard", to: "pages#dashboard"
  resources :private_chatrooms, only: [:show, :new, :create] do
    resources :private_messages, only: [:create, :destroy]
  end

  resources :jobs do
    resources :job_responses, only: [:new, :create]
  end
  resources :job_responses, only: [:show, :new, :update, :destroy]

  resources :tags
  resources :blogs do
    resources :blog_posts do
      resources :comments
      resources :votes
    end
  end

  resources :categories, only: [:index, :show]

  get "new_messages", to: "private_messages#new_messages"
  get "read_messages", to: "private_messages#read_messages"
  post "read_messages", to: "private_messages#read_messages"

  resources :jobs, only: [:index, :show] do
    member do
      post 'toggle_favorite', to: "jobs#toggle_favorite"
    end
  end
  # Define your job_responses routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/job.rb
class Job < ApplicationRecord
  acts_as_favoritable
  validates :title, :content, :location, :summary, :salary, presence: true
  belongs_to :user
  has_many :job_responses, dependent: :destroy
  has_many :job_tags, dependent: :destroy
  has_many :tags, through: :job_tags
  validates :title, :content, :location, presence: true
  has_one_attached :image

  include PgSearch::Model
  pg_search_scope :search_by_title_content_location,
    against: [:title, :content, :location],
    associated_against: {
      tags: [:name]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy, :toggle_favorite]

  def index
    @jobs = policy_scope(Job)
    if params[:query].present?
      @query = params[:query]
      @jobs = Job.search_by_title_content_location(@query)
    else
      @jobs = Job.all
      @jobs = tagged_jobs(@jobs) if params[:tag_id]

    end

  end

  def show
  end

  def new
    @job = Job.new
    authorize @job
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user
    authorize @job
    if params[:job][:tags].present?
      params[:job][:tags].each do |tag|
        @job.tags << Tag.find(tag)
      end
    end
    if @job.save
      redirect_to job_path(@job)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @job.update(job_params)
    if params[:job][:summary].present?
      respond_to do |format|
        format.html { redirect_to job_path(@job) }
        format.text { render partial: "job_summary", locals: {job: @job}, formats: [:html] }
      end
    elsif params[:job][:title].present?
      respond_to do |format|
        format.html { redirect_to job_path(@job) }
        format.text { render partial: "job_title", locals: {job: @job}, formats: [:html] }
      end
    elsif params[:job][:content].present?
      respond_to do |format|
        format.html { redirect_to job_path(@job) }
        format.text { render partial: "job_content", locals: {job: @job}, formats: [:html] }
      end
    elsif params[:job][:salary].present?
      respond_to do |format|
        format.html { redirect_to job_path(@job) }
        format.text { render partial: "job_salary", locals: {job: @job}, formats: [:html] }
      end
    elsif params[:job][:location].present?
      respond_to do |format|
        format.html { redirect_to job_path(@job) }
        format.text { render partial: "job_location", locals: {job: @job}, formats: [:html] }
      end
    else
      respond_to do |format|
        format.html { redirect_to job_path(@job) }
      end
    end
  end

  def toggle_favorite
    current_user.favorited?(@job)  ?
    current_user.unfavorite(@job) : current_user.favorite(@job)
  end

  def destroy
    @job.destroy
    redirect_to jobs_path, status: :see_other
  end

  private

  def set_job
    @job = Job.find(params[:id])
    authorize @job
  end

  def job_params
    params.require(:job).permit(:title, :location, :content, :salary, :summary, :company_name, :image)
  end

  def tagged_jobs(jobs)
    jobs.joins(:job_tags)
        .joins(:tags)
        .where('tags.id = ?', params[:tag_id])
  end
end

app/views/jobs/_filter.html.erb
<div class="search-filters-container col-3">
  <div>
    <p class="filter-header">Filter</p>
    <% if @query %>
        <p>You searched for <strong><%= @query %></strong>. We found <%= @jobs.count %> jobs matching your search.</p>
    <% else %>
        <p>Search <strong><%= @jobs.count %></strong> job postings.</p>
    <% end %>
    </div>

    <div class="search-form-and-filter-buttons">
      <div class="search-form">
        <form class="input-group rounded">
          <input class="form-control rounded input-field-search" name="query" type="search" placeholder="Company, skill ..." autocomplete="off" aria-label="Search" value="<%= params[:query] %> ">
          <div class="filter-tags">
            <% Tag.all.each do |tag|%>
            <div class="form-check tags">
              <input class="form-check-input tag-button" type="radio" name="exampleRadios" id= "<%= tag.name %>" value="option1" checked>
              <label class="form-check-label" for="<%= tag.name %>" style="<%= 'background-color: #042454; color: white;' if params[:tag_id].to_i == tag.id %>">
                  <%= link_to tag.name, jobs_path(tag_id: tag.id) %>
              </label>
            </div>
            <% end %>
          </div>
        <button class="input-group-text border-0 search-button-filter" type="submit">Search</button>
      </form>
    </div>
  </div>
</div>

app/views/jobs/_job.html.erb
<div class="job-card-index" id="<%= dom_id job %>">
  <div class="job-card-image-and-contents">
    <%  if job.image.attached? %>
      <%= cl_image_tag job.image.key, class: "job-card-logo-index" %>
    <% else %>
      <img class="job-card-logo-index" alt="logo" src="/assets/logo_placeholder-c7c60a6d1a473197b91b4be9dc89f71b2fcc132219fd83708de2fcc91fe40cb6.png">
    <% end %>
    <div class="index-card-contents">
      <p class="job-card-index-heading"><%= job.title %></p>
      <p class="job-card-index-content"><%= job.summary %></p>
      <p class="job-card-index-location"><i class="fa-solid fa-location-dot"> </i><%= job.location %></p>
    </div>
  </div>
  <div class="card-buttons ">
    <%= link_to "View Job", job_path(job), class: "btn btn-light job-card-index-more-info" if policy(Job).show? %>
    <%# Logic for buttons %>
    <%# job_response = current_user.job_responses.where(job: job).first %>
    <% if current_user.job_responses.where(job: job).empty? %>
      <% if current_user.jobs.where(id: job.id).empty? %>
        <%# Apply button %>
      <%= link_to "Apply", job_path(job), class: "btn btn-light job-card-index-apply" if policy(Job).show?  %>
      <% else %>
        <%# Your ad badge %>
        <span class="badge text-bg-warning m-1">Your ad</span>
      <% end %>
    <% end %>
    <%# Logic for badges for applicant%>
    <% job_response = current_user.job_responses.where(job: job).first %>
    <% if job_response.nil? == false %>
      <% if job_response.status == "accepted" %>
        <span class="badge text bg-success m-1">Accepted</span>
      <% elsif job_response.status == "declined" %>
        <span class="badge text bg-danger m-1">Declined</span>
      <% else %>
        <span class="badge text bg-warning m-1">Pending</span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/jobs/_job_content.html.erb
<div data-edit-job-posting-target="content">
  <div data-edit-job-posting-target="contentinfos">
    <p><%= @job.content.html_safe %><button aria-label="Edit content"><i class="fa-solid fa-pen" data-action="click->edit-job-posting#displayFormContent"></i>
  </button></p>
  </div>

<%= simple_form_for job,
  html: {
    class: "d-none",
    data: {
      edit_job_posting_target: "formcontent",
      action: "submit->edit-job-posting#updateContent"
    }

  } do |f| %>

    <%= f.input :content %>
    <%= f.button :submit, "Submit", class:"btn1 mt-3 mb-3"%>
  <% end %>

</div>

app/views/jobs/_job_location.html.erb
<div data-edit-job-posting-target="location">
  <div data-edit-job-posting-target="locationinfos">
   <p class="job-card-index-location"><i class="fa-solid fa-location-dot"> </i><%= @job.location %><button aria-label="Edit location"><i class="fa-solid fa-pen" data-action="click->edit-job-posting#displayFormLocation"></i>
  </button></p>
  </div>

<%= simple_form_for job,
  html: {
    class: "d-none",
    data: {
      edit_job_posting_target: "formlocation",
      action: "submit->edit-job-posting#updateLocation"
    }

  } do |f| %>

    <%= f.input :location %>
    <%= f.button :submit, "Submit", class:"btn1 mt-3 mb-3"%>
  <% end %>

</div>

app/views/jobs/_job_salary.html.erb
<div data-edit-job-posting-target="salary">
  <div data-edit-job-posting-target="salaryinfos">
    <p><%= @job.salary %> €<button aria-label="Edit content"><i class="fa-solid fa-pen" data-action="click->edit-job-posting#displayFormSalary"></i>
  </button></p>
  </div>

<%= simple_form_for job,
  html: {
    class: "d-none",
    data: {
      edit_job_posting_target: "formsalary",
      action: "submit->edit-job-posting#updateSalary"
    }

  } do |f| %>

    <%= f.input :salary %>
    <%= f.button :submit, "Submit", class:"btn1 mt-3 mb-3"%>
  <% end %>

</div>

app/views/jobs/_job_summary.html.erb
<div class="job-summary" data-edit-job-posting-target="summary">
  <div data-edit-job-posting-target="infos"><h5>Summary <button aria-label="Edit summary"><i class="fa-solid fa-pen" data-action="click->edit-job-posting#displayForm"></i>
  </button></h5>
  <p><%= job.summary %></p>
  <%# cannot use @job inside partial %>
  </div>

  <%= simple_form_for job,
  html: {
    class: "d-none",
    data: {
      edit_job_posting_target: "form",
      action: "submit->edit-job-posting#updateSummary"
    }

  } do |f| %>

    <%= f.input :summary %>
    <%= f.button :submit, "Submit", class:"btn1 mt-3 mb-3"%>
  <% end %>
</div>

app/views/jobs/_job_title.html.erb
<div data-edit-job-posting-target="title">
  <div data-edit-job-posting-target="titleinfos">
    <h2><%= job.title %><button aria-label="Edit title"><i class="fa-solid fa-pen" data-action="click->edit-job-posting#displayFormTitle"></i>
  </button></h2>
  </div>

<%= simple_form_for job,
  html: {
    class: "d-none",
    data: {
      edit_job_posting_target: "formtitle",
      action: "submit->edit-job-posting#updateTitle"
    }

  } do |f| %>

    <%= f.input :title %>
    <%= f.button :submit, "Submit", class:"btn1 mt-3 mb-3"%>
  <% end %>

</div>

app/views/jobs/edit.html.erb
<%= simple_form_for @job do |f| %>
  <%= f.input :company_name %>
  <%= f.input :image, as: :file %>
  <%= f.input :title %>
  <%= f.input :location %>
  <%= f.input :summary %>
  <%= f.input :content %>
  <%= f.input :salary %>
  <%= f.button :submit, "Submit", class:"btn1 mt-3 mb-3"%>
<% end %>

app/views/jobs/index.html.erb
<div class="container">
  <div class="new-opportunities-heading">
    <p>New job opportunities</p>
    <div class="post-a-job">
      <button type="button" class="btn btn-light
      input-group-text border-0 new-job-button">
        <% if current_user.company == true %>
          <%= link_to "+ Post a job", new_job_path if policy(Job).new? %>
        <% end %>
      </button>
    </div>
  </div>
  <div class="container-list-and-filter row">
      <div class="job-listings-container col-9">
          <div class="row">
            <% @jobs.uniq.each do |job| %>
            <%= render "job", job: job, job_response: nil %>
            <% end %>
          </div>
      </div>
    <%= render "filter" %>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="container">
  <%= simple_form_for @job do |f| %>
    <%= f.input :company_name %>
    <%= f.input :title %>
    <%= f.input :location %>
    <%= f.input :summary %>
    <%= f.input :content %>
    <%= f.input :salary %>
    <%= f.input :tags, as: :check_boxes, collection: Tag.all, label: "Tags", include_hidden: false %>
    <%= f.input :image, as: :file %>
    <%= f.button :submit, "Submit", class:"btn1 mt-3 mb-3"%>

  <% end %>
</div>

app/views/jobs/show.html.erb
<div class="job-posting" data-controller="edit-job-posting">
<%# row is divided in 2 parts: side and main %>

          <%# SIDE SECTION - AVATAR AND KEY POINTS %>
  <div class="side">
    <%  if @job.image.attached? %>
      <%= cl_image_tag @job.image.key, class: "job-logo" %>
    <% else %>
      <img class="job-logo" alt="logo" src="/assets/logo_placeholder-c7c60a6d1a473197b91b4be9dc89f71b2fcc132219fd83708de2fcc91fe40cb6.png">
    <% end %>
    <div class="job-key-points">
      <h5>Annual Salary</h5>
        <%= render "job_salary", job: @job %>
      <h5>Languages</h5>
        <p class="language">English</p>
      <h5>Location</h5>
        <%= render "job_location", job: @job %>
    </div>
  </div>

  <div class="main" data-controller="favorite">

    <div><%= link_to "Apply", new_job_job_response_path(@job), class: "btn btn-light job-card-index-apply" if policy(Job).show?%>
    </div>

    <div class="delete-button">  <%= button_to "Delete", @job, method: :delete if policy(@job).destroy?%>
    </div>
    <div><%= link_to "Edit", edit_job_path(@job), class: "btn edit-job-button" if policy(Job).edit?%>
    </div>


    <div class="bookmark-button">
      <%= link_to toggle_favorite_job_path(@job), data: { "turbo-method": :post }  do %>
        <i data-favorite-target="bookmark" data-action="click->favorite#toggleFavorite" class="fa-solid fa-heart <%='red' if current_user.favorited?(@job) %>"></i>
      <% end %>

    </div>
          <%# MAIN SECTION - JOB SUMMARY AND DESCRIPTION %>
          <div class="job-details">

            <div class="company-name"><%= @job.company_name %></div>
            <%= render "job_summary", job: @job %>

            <div class="job-description">

              <%= render "job_title", job: @job %>
              <%= render "job_content", job: @job %>

              <div class="job-show-contacts">
              <h6> Recruiter:

              </h6>
              <p>
                <%=  link_to @job.user.profile.name, profile_path(@job.user)%><%= link_to profile_path(@job.user) do %>
                <i class="fa-solid fa-eye">&nbsp;</i>
                <% end %>
              </p>
            </div>
            </div>


          </div>
        </div>

    </div>



  <!-- [...] -->


</div>