config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :jobs
  resources :job_responses
  resources :profiles, only: [:index,:show, :edit, :update]
  resources :chatrooms, only: [:show, :new, :create] do
    resources :messages, only: :create
  end
  get "dashboard", to: "pages#dashboard"
  resources :private_chatrooms, only: [:show, :new, :create] do
    resources :private_messages, only: [:create, :destroy]
  end

  resources :jobs do
    resources :job_responses, only: [:new, :create]
  end
  resources :job_responses, only: [:show, :new, :update, :destroy]

  resources :tags
  resources :blogs do
    resources :blog_posts do
      resources :comments
      resources :votes
    end
  end

  resources :categories, only: [:index, :show]

  get "new_messages", to: "private_messages#new_messages"
  get "read_messages", to: "private_messages#read_messages"
  post "read_messages", to: "private_messages#read_messages"

  resources :jobs, only: [:index, :show] do
    member do
      post 'toggle_favorite', to: "jobs#toggle_favorite"
    end
  end
  # Define your job_responses routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
  has_many :blog_posts, dependent: :destroy
  has_many :blogs_tags, dependent: :destroy
  has_many :tags, through: :blogs_tags
  has_many :blog_categories, dependent: :destroy
  has_many :categories, through: :blog_categories
  has_one_attached :image
end

app/models/blog_category.rb
class BlogCategory < ApplicationRecord
  belongs_to :blog
  belongs_to :category
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :blog, optional: true
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_one_attached :image
  has_many :blog_post_categories, dependent: :destroy
  has_many :categories, through: :blog_post_categories

  include PgSearch::Model
  pg_search_scope :search_by_title,
    against: [ :title ],
    associated_against: {
      # blog: [:.user.nickname],
      categories: [:name]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/blogs_tag.rb
class BlogsTag < ApplicationRecord
  belongs_to :blog
  belongs_to :tag
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :blog_categories, dependent: :destroy
  has_many :blogs, through: :blog_categories
  has_many :blog_post_categories, dependent: :destroy
  has_many :blog_posts, through: :blog_post_categories
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :blog_post
  has_many :comments, foreign_key: :parent_id, dependent: :destroy
  belongs_to :parent, class_name: 'Comment', optional: true
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/job.rb
class Job < ApplicationRecord
  acts_as_favoritable
  validates :title, :content, :location, :summary, :salary, presence: true
  belongs_to :user
  has_many :job_responses, dependent: :destroy
  has_many :job_tags, dependent: :destroy
  has_many :tags, through: :job_tags
  validates :title, :content, :location, presence: true
  has_one_attached :image

  include PgSearch::Model
  pg_search_scope :search_by_title_content_location,
    against: [:title, :content, :location],
    associated_against: {
      tags: [:name]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/job_response.rb
class JobResponse < ApplicationRecord
  validates :user_id, :job_id, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_one_attached :cv
  validates :cv, presence: true
  enum status: [ :draft, :pending, :accepted, :declined ]
  belongs_to :user
  belongs_to :job
end

app/models/job_tag.rb
class JobTag < ApplicationRecord
  belongs_to :job
  belongs_to :tag
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/private_chatroom.rb
class PrivateChatroom < ApplicationRecord
  belongs_to :user_sender, class_name: "User"
  belongs_to :user_reciever, class_name: "User"
  has_many :private_messages, dependent: :destroy
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :user
  belongs_to :private_chatroom
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  has_many :job_tags, dependent: :destroy
  has_many :jobs, through: :job_tags
  has_many :blogs, through: :blog_posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_favoritor
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true, uniqueness: true, length: { minimum: 3, maximum: 20 }
  has_many :job_responses
  has_many :jobs, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_one :vote, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :blogs, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :private_chatrooms_as_sender, class_name: "PrivateChatroom", foreign_key: "user_sender_id", dependent: :destroy
  has_many :private_chatrooms_as_reciever, class_name: "PrivateChatroom", foreign_key: "user_reciever_id", dependent: :destroy
  before_create :build_profile

  def find_private_chat(user)
    PrivateChatroom.find_by(user_sender: user, user_reciever: self) || PrivateChatroom.find_by(user_sender: self, user_reciever: user)
  end

  def private_chatrooms
    (private_chatrooms_as_sender + private_chatrooms_as_reciever).uniq
  end

  def new_messages
    my_chats = private_chatrooms
    # array of messages where user is not current_user and message new is true
    new_messages = []
    my_chats.each do |chat|
      chat.private_messages.each do |message|
        new_messages << message if message.user != self && message.new
      end
    end
    new_messages
  end

  def new_messages_from_user(user_id)
    messages = new_messages
    messages.select { |message| message.user_id == user_id }
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :blog_post
  validates :user_id, uniqueness: { scope: :blog_post_id }
end

app/helpers/button_helper.rb
module ButtonHelper
  def voted(blog, blog_post)
    vote = Vote.find_by(user: current_user, blog_post: blog_post)
    if vote
      button_to blog_blog_post_vote_path(blog, blog_post, blog_post.votes.where(user: current_user).first, value: 1), method: :patch, class: "like" do
        '<i class="fa-solid fa-heart"></i>'.html_safe
      end

      button_to blog_blog_post_vote_path(blog, blog_post, blog_post.votes.where(user: current_user).first, value: -1), method: :patch, class: "dislike" do
        '<i class="fa-solid fa-heart-crack"></i>'.html_safe
      end
    else
      button_to blog_blog_post_vote_path(blog, blog_post, value: 1), method: :post, class: "like" do
        '<i class="fa-solid fa-heart"></i>'.html_safe
      end
      button_to blog_blog_post_vote_path(blog, blog_post, value: -1), method: :post, class: "dislike" do
        '<i class="fa-solid fa-heart-crack"></i>'.html_safe
      end
    end
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="Brand">
    <h2>JuniorHub</h2>
  </div>
  <div class="footer-menu">
    <div class="fm">
      <%= link_to "Home", "#", class: "footer-button" %>
      <%= link_to "About", "#", class: "footer-button" %>
      <%= link_to "Contact", "#", class: "footer-button" %>
      <% if user_signed_in? %>
        <%= link_to "Jobs", "#", class: "footer-button" %>
        <%= link_to "Profile", "#", class: "footer-button" %>
        <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "footer-button" %>
      <% end %>
    </div>
  </div>
  <div class="last_row">
    <div class="footer-links">
      <div>
        <a href="#"><i class="fab fa-github"></i></a>
      </div>
      <div>
        <a href="#"><i class="fab fa-instagram"></i></a>
      </div>
      <div>
        <a href="#"><i class="fab fa-facebook"></i></a>
      </div>
      <div>
        <a href="#"><i class="fab fa-twitter"></i></a>
      </div>
      <div>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>
    <div class="footer-copyright">
      Copyright © 2022 <strong>JuniorHub</strong>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
    <nav>
      <a href="/">
        <div class="logo">
            <%= image_tag "JH-logo.png", class:"JH-logo", alt:"logo" %>
        </div>
      </a>
      <ul class="nav-links">
        <% if user_signed_in? %>
          <li>
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Jobs", jobs_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Profiles", profiles_path, class: "nav-link" %>
          </li>
          <li>
            <button type="button" class="btn btn-link nav-link" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Chat
            </button>
            <%#= link_to "Chat", chatroom_path(Chatroom.all.first), class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Blogs", blogs_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "#{current_user.nickname}", "/dashboard", class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign-up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <div class="burger" data-controller="navbar" data-action="click->navbar#navSlide">
        <div class="line1"></div>
        <div class="line2"></div>
        <div class="line3"></div>
      </div>
    </nav>
<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Chat</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render "chatrooms/chatroom", chatroom: Chatroom.all.first, message: Message.new %>
      </div>
    </div>
  </div>
</div>